export type CoreErrorCode =
  | "INVALID_COMMAND"
  | "MOVEMENT_NOT_FOUND"
  | "MOVEMENT_ALREADY_INACTIVE"
  | "MOVEMENT_NOT_DELETED"
  | "MOVEMENT_REVERSED_NOT_RESTORABLE"
  | "MOVEMENT_REQUIRES_SPECIALIZED_ENGINE"
  | "INVALID_MOVEMENT_AMOUNT"
  | "INVALID_MOVEMENT_ACCOUNTS"
  | "INVALID_MOVEMENT_BOXES"
  | "INVALID_ADJUSTMENT"
  | "DEBT_PAYMENT_HANDLER_UNAVAILABLE"
  | "DEBT_NOT_FOUND"
  | "DEBT_NOT_ACTIVE"
  | "DEBT_PAYMENT_EXCEEDS_BALANCE"
  | "DEBT_PAYMENT_CURRENCY_MISMATCH"
  | "DEBT_PAYMENT_ACCOUNT_NOT_FOUND"
  | "DEBT_PAYMENT_ACCOUNT_CURRENCY_MISMATCH"
  | "DEBT_INSTALLMENT_NOT_FOUND"
  | "DEBT_INSTALLMENT_NOT_ACTIONABLE"
  | "DEBT_PAYMENT_IDEMPOTENCY_CONFLICT"
  | "DEBT_CREATION_HANDLER_UNAVAILABLE"
  | "DEBT_CREATION_ACCOUNT_NOT_FOUND"
  | "DEBT_CREATION_ACCOUNT_CURRENCY_MISMATCH"
  | "DEBT_CREATION_IDEMPOTENCY_KEY_REQUIRED"
  | "DEBT_CREATION_IDEMPOTENCY_CONFLICT"
  | "DEBT_CREATION_INVALID_AMOUNT"
  | "DEBT_CREATION_INVALID_CURRENCY"
  | "DEBT_CREATION_INVALID_INSTALLMENTS"
  | "DEBT_CREATION_INVALID_DIRECTION"
  | "DEBT_CREATION_INVALID_RESULT"
  | "CORE_REPOSITORY_ERROR";

export class CoreError extends Error {
  readonly code: CoreErrorCode;
  readonly details: Record<string, unknown>;

  constructor(
    code: CoreErrorCode,
    message: string,
    details: Record<string, unknown> = {}
  ) {
    super(message);
    this.name = "CoreError";
    this.code = code;
    this.details = details;
  }
}
